[package]
name = "sharp"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
crate-type = ["staticlib"]

[dependencies]
mago-sharp-bridge = { git = "https://github.com/heyJordanParker/mago-sharp", rev = "0f7dc46623c29f03770d5805e51b76836281bd22" }

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
