[package]
name = "sharp"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
crate-type = ["staticlib"]

[dependencies]
mago-sharp-bridge = { git = "https://github.com/heyJordanParker/mago", rev = "6e3346780cafed1452b3edb5cec2875419893bbd" }

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
