[package]
name = "sharp"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
crate-type = ["staticlib"]

[dependencies]
mago-sharp-bridge = { git = "https://github.com/heyJordanParker/mago", rev = "3c3b3dc751230c2fcb3bd9a120dc79bafff221c0" }

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
